# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d92dd54c79aca80bd0feadab42b7f7ebf36b4cbd900d6bc12f61142631b7efa63b6614fe83da03cabef5e252425dcc6db38298fb2235bf536b8ed379da7d7361

test:
  secret_key_base: d0517cf742c95ccbb320967db593a6748f5fbad015dc60f12bfe20ef580582a20b814c5be24a5957a7f9fcf690b4a0709fce5096a84712efb959d431d1b2e89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
